app:
  port: 3000
  debug: true
  max_file_size: 10

service:
  backend: localhost:3001
  auth: localhost:3002
  file: localhost:3003

vaccine:
  host: localhost:8000
  api_key: <api key>

guard:
  phase: "register"