name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - beta
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  GITOPS_REPO: isd-sgcu/rnkm65-gitOps
  GITOPS_BASE_PATH: environment
  GITOPS_SERVICE_NAME: gateway

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      BRANCH: ${{ steps.branch.outputs.BRANCH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set branch
        id: branch
        run: |
          echo "::set-output name=BRANCH::${GITHUB_REF#refs/heads/}"

      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          ssh-key: ${{ secrets.GITOPS_SSH_KEY }}

      - name: "Setup Kustomize"
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_build_dir: ${{ env.GITOPS_BASE_PATH }}/${{ needs.build.outputs.BRANCH }}/${{ env.GITOPS_SERVICE_NAME }}

      - name: Set image
        working-directory: ${{ env.GITOPS_BASE_PATH }}/${{ needs.build.outputs.BRANCH }}/${{ env.GITOPS_SERVICE_NAME }}
        run: |
          kustomize edit set image ${{ env.IMAGE_NAME }}=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Set `${{ env.GITOPS_SERVICE_NAME }}` image tag to `${{ env.IMAGE_TAG }}`"
